// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "carAPI/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCarStore is a mock of CarStore interface.
type MockCarStore struct {
	ctrl     *gomock.Controller
	recorder *MockCarStoreMockRecorder
}

// MockCarStoreMockRecorder is the mock recorder for MockCarStore.
type MockCarStoreMockRecorder struct {
	mock *MockCarStore
}

// NewMockCarStore creates a new mock instance.
func NewMockCarStore(ctrl *gomock.Controller) *MockCarStore {
	mock := &MockCarStore{ctrl: ctrl}
	mock.recorder = &MockCarStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarStore) EXPECT() *MockCarStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCarStore) Create(car *model.Car) (*model.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", car)
	ret0, _ := ret[0].(*model.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCarStoreMockRecorder) Create(car interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCarStore)(nil).Create), car)
}

// Delete mocks base method.
func (m *MockCarStore) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCarStoreMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCarStore)(nil).Delete), id)
}

// GetByBrand mocks base method.
func (m *MockCarStore) GetByBrand(brand string) ([]model.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBrand", brand)
	ret0, _ := ret[0].([]model.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBrand indicates an expected call of GetByBrand.
func (mr *MockCarStoreMockRecorder) GetByBrand(brand interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBrand", reflect.TypeOf((*MockCarStore)(nil).GetByBrand), brand)
}

// GetByID mocks base method.
func (m *MockCarStore) GetByID(id string) (*model.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCarStoreMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCarStore)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockCarStore) Update(car *model.Car) (*model.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", car)
	ret0, _ := ret[0].(*model.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCarStoreMockRecorder) Update(car interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCarStore)(nil).Update), car)
}

// MockEngineStore is a mock of EngineStore interface.
type MockEngineStore struct {
	ctrl     *gomock.Controller
	recorder *MockEngineStoreMockRecorder
}

// MockEngineStoreMockRecorder is the mock recorder for MockEngineStore.
type MockEngineStoreMockRecorder struct {
	mock *MockEngineStore
}

// NewMockEngineStore creates a new mock instance.
func NewMockEngineStore(ctrl *gomock.Controller) *MockEngineStore {
	mock := &MockEngineStore{ctrl: ctrl}
	mock.recorder = &MockEngineStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineStore) EXPECT() *MockEngineStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEngineStore) Create(engine *model.Engine) (*model.Engine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", engine)
	ret0, _ := ret[0].(*model.Engine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEngineStoreMockRecorder) Create(engine interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEngineStore)(nil).Create), engine)
}

// Delete mocks base method.
func (m *MockEngineStore) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEngineStoreMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEngineStore)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockEngineStore) GetAll() (map[string]model.Engine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[string]model.Engine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockEngineStoreMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEngineStore)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockEngineStore) GetByID(id string) (*model.Engine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.Engine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEngineStoreMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEngineStore)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockEngineStore) Update(engine *model.Engine) (*model.Engine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", engine)
	ret0, _ := ret[0].(*model.Engine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEngineStoreMockRecorder) Update(engine interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEngineStore)(nil).Update), engine)
}
